[workspace]
members = [
    "cli",
    "codegen",
    "testing/substrate-runner",
    "testing/test-runtime",
    "testing/integration-tests",
    "testing/ui-tests",
    "macro",
    "metadata",
    "signer",
    "subxt"
]

# We exclude any crates that would depend on non mutually
# exclusive feature flags and thus can't compile with the
# workspace:
exclude = [
    "testing/wasm-tests",
    "signer/wasm-tests",
    "examples/wasm-example"
]
resolver = "2"

[workspace.package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
version = "0.29.0"
rust-version = "1.64.0"
license = "Apache-2.0 OR GPL-3.0"
repository = "https://github.com/paritytech/subxt"
documentation = "https://docs.rs/subxt"
homepage = "https://www.parity.io/"

[workspace.dependencies]
assert_matches = "1.5.0"
base58 = { version = "0.2.0" }
bitvec = { version = "1", default-features = false }
blake2 = { version = "0.10.4", default-features = false }
clap = { version = "4.3.10", features = ["derive", "cargo"] }
criterion = "0.4"
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false }
color-eyre = "0.6.1"
console_error_panic_hook = "0.1.7"
darling = "0.20.0"
derivative = "2.2.0"
either = "1.8.1"
frame-metadata = { version = "15.1.0", features = ["v14", "v15-unstable", "std"] }
futures = { version = "0.3.27", default-features = false, features = ["std"] }
getrandom = { version = "0.2", default-features = false }
hex = "0.4.3"
heck = "0.4.1"
impl-serde = { version = "0.4.0" }
jsonrpsee = { version = "0.16" }
pretty_assertions = "1.0.0"
primitive-types = { version = "0.12.1", default-features = false, features = ["codec", "scale-info", "serde"] }
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.63"
quote = "1.0.29"
regex = "1.8.4"
scale-info = "2.8.0"
scale-value = "0.10.0"
scale-bits = "0.3"
scale-decode = "0.7.0"
scale-encode = "0.3.0"
serde = { version = "1.0.164" }
serde_json = { version = "1.0.99" }
syn = { version = "2.0.15", features = ["full", "extra-traits"] }
thiserror = "1.0.40"
tokio = { version = "1.29", features = ["macros", "time", "rt-multi-thread"] }
tracing = "0.1.34"
tracing-wasm = "0.2.1"
tracing-subscriber = "0.3.17"
trybuild = "1.0.79"
wabt = "0.10.0"
wasm-bindgen-test = "0.3.24"
which = "4.4.0"

# Light client support:
smoldot-light = { version = "0.6.0", default-features = false }
tokio-stream = "0.1.14"
futures-util = "0.3.28"

# Substrate crates:
sp-core = { version = "21.0.0", default-features = false }
sp-core-hashing = "9.0.0"
sp-runtime = "24.0.0"
sp-keyring = "24.0.0"
sp-version = "22.0.0"

# Subxt workspace crates:
subxt = { version = "0.29.0", path = "subxt", default-features = false }
subxt-macro = { version = "0.29.0", path = "macro" }
subxt-metadata = { version = "0.29.0", path = "metadata" }
subxt-codegen = { version = "0.29.0", path = "codegen" }
subxt-signer = { version = "0.29.0", path = "signer" }
test-runtime = { path = "testing/test-runtime" }
substrate-runner = { path = "testing/substrate-runner" }

# subxt-signer deps that I expect aren't useful anywhere else:
bip39 = "2.0.0"
hmac = "0.12.1"
pbkdf2 = { version = "0.12.2", default-features = false }
schnorrkel = "0.10.2"
secrecy = "0.8.0"
sha2 = "0.10.6"
zeroize = { version = "1", default-features = false }